const data = {
  ads: [
    /*----decoration(pic)----*/
    {
      name: '2 abstract pictures', // ad name
      slug: '2-abstract-pictures', // what we see in the URL
      category: 'decoration',
      image: '/images/pic/2picGolf.jpg', // 679px × 829px
      countInStock: 10,
      brand: 'Golf&co',
      rating: 4.5,
      numReviews: 10,
      description: 'Well kept and undamaged',
    },
    {
      name: '2 blue pictures',
      slug: '2 blue pictures',
      category: 'decoration',
      image: '/images/pic/2blue_pictures.jpg',
      countInStock: 20,
      brand: '/',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: '2 handmade pictures',
      slug: '2 handmade pictures',
      category: 'decoration',
      image: '/images/pic/2small_handmade_pictures.jpg',
      countInStock: 20,
      brand: 'handmade',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality handmade product',
    },
    {
      name: '4 pictures',
      slug: '4 pictures',
      category: 'decoration',
      image: '/images/pic/4pic.jpg',
      countInStock: 20,
      brand: '/',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: '9 handmade pictures',
      slug: '',
      category: 'decoration',
      image: '/images/pic/9small_handmade_pictures.jpg',
      countInStock: 20,
      brand: 'handmade',
      rating: 4.0,
      numReviews: 10,
      description: '9 handmade pictures',
    },
    /*----garden----*/
    {
      name: '2 vases',
      slug: '2 vases',
      category: 'garden',
      image: '/images/garden/2vases.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: '3 flower pots',
      slug: '3 flower pots',
      category: 'garden',
      image: '/images/garden/3flower_pots.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'bottom for flower pot',
      slug: 'bottom for flower pot',
      category: 'garden',
      image: '/images/garden/bottom_for_flower_pot.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: '13 cm',
    },
    {
      name: 'cow pot',
      slug: 'cow pot',
      category: 'garden',
      image: '/images/garden/cow_pot.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'fence growing cherry tomatoes',
      slug: 'fence growing cherry tomatoes',
      category: 'garden',
      image: '/images/garden/fence_growing_cherry_tomatoes.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: '..',
    },
    {
      name: 'Ficus tree',
      slug: 'Ficus tree',
      category: 'garden',
      image: '/images/garden/Ficus_ficus_tree.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: 'Ficus tree with the pot',
    },
    {
      name: 'Garden gnome',
      slug: 'Garden gnome',
      category: 'garden',
      image: '/images/garden/Garden_gnomes.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: '9 objects',
    },
    {
      name: 'yellow flower pot',
      slug: 'yellow flower pot',
      category: 'garden',
      image: '/images/garden/yellowFlowerpot.jpg',
      countInStock: 15,
      brand: '/',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
  ],
};
export default data;
